// src/widgets/button/button.tsx
import React, { FunctionComponent } from "react";
import css from "./button.module.scss";

type Props = {
	cls?: string;
	type?: string;
	link?: string;
	onClick?: () => void;
};

const Button: FunctionComponent<Props> = ({
	children,
	cls = "",
	type = "",
	link = "",
	onClick,
}) =>
	link ? (
		<a
			href={link}
			className={`${cls} ${css.base} ${css.link} ${
				type ? css[type as keyof typeof css] : ""
			}`}
			rel="noreferrer noopener"
			target="_blank"
		>
			{children}
		</a>
	) : (
		<button
			onClick={onClick}
			className={`${cls} ${css.base} ${
				type ? css[type as keyof typeof css] : ""
			}`}
		>
			{children}
		</button>
	);
export default Button;

// src/components/Button.svelte
<script lang="ts">
	export let type: "button" | "submit" | "reset" = "button";
	export let link: string = '';
	export let onClick: () => void = undefined;
	export let css: string = "";
</script>

{#if link}
	<a
		class={`btn ${css}`}
		href={link}
		rel="noreferrer noopener"
		target="_blank"
	>
		<slot />
	</a>
{:else}
	<button {onClick} {type} class={`btn ${css}`}>
		<slot />
	</button>
{/if}

<style lang="scss">
	.btn {
		font-size: var(--ft-18);
		padding: 0.5em;
		cursor: pointer;
		text-decoration: none;
		background: none;
		transition: background 0.3s, color 0.3s, opacity 0.3s;
		&:hover {
			color: var(--primary);
			opacity: 1;
		}
	}
</style>
